force-app/main/default/objects/ObjectA__c/ObjectA__c.object-meta.xml
<CustomObject>
    <label>ObjectA</label>
    <nameField>
        <label>ObjectA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ObjectAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjectB__c/ObjectB__c.object-meta.xml
<CustomObject>
    <label>ObjectB</label>
    <nameField>
        <label>ObjectB Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ObjectBs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjectB__c/fields/ObjectA__c.field-meta.xml
<CustomField>
    <fullName>ObjectA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ObjectA</label>
    <referenceTo>ObjectA__c</referenceTo>
    <relationshipLabel>ObjectBs</relationshipLabel>
    <relationshipName>ObjectBs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ObjectC__c/ObjectC__c.object-meta.xml
<CustomObject>
    <label>ObjectC</label>
    <nameField>
        <label>ObjectC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ObjectCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjectC__c/fields/ObjectB__c.field-meta.xml
<CustomField>
    <fullName>ObjectB__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ObjectB</label>
    <referenceTo>ObjectB__c</referenceTo>
    <relationshipLabel>ObjectCs</relationshipLabel>
    <relationshipName>ObjectCs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RecordsListControllerTest.cls
@isTest(SeeAllData = true)
public with sharing class RecordsListControllerTest {
    @isTest static void testObjectList() {
        
        //Create ojbectA
        ObjectA__c obja = new ObjectA__c(Name = 'Example');
        insert obja;

        //Save Id of objectA
        ID objaid = obja.id;
        system.debug('id'+objaid);
      

        //Create list of objectb
        List < ObjectB__c > objectsb = new List < ObjectB__c > ();
        for (Integer count = 0; count < 3; count++) {
            objectsb.add(new ObjectB__c(Name = 'Jack' + count, Phone__c = '910294830000', ObjectA__c =objaid) );
        }
        insert objectsb;
      
       ID objbid = objectsb[0].id;
  
        ////Create list of objectC
        List < ObjectC__c > objectsc = new List < ObjectC__c > ();
        for (Integer count = 0; count < 3; count++) {
            objectsc.add(new ObjectC__c(Name = 'Jack' + count, Phone__c = '910294830000', objectB__c = objbid));
        }
        insert objectsc;

        Test.startTest();
        List < ObjectB__c > recordsb = RecordsListController.getObjectsB(objaid);
        List < ObjectC__c > recordsc = RecordsListController.getObjectsC(objaid);
        system.debug(recordsb.size());

        Test.stopTest();
        
         System.assertEquals(recordsb.size(), 3);
         System.assertEquals(recordsc.size(), 3);
       

    }

}