force-app/main/default/objects/ObjectA__c/ObjectA__c.object-meta.xml
<CustomObject>
    <label>ObjectA</label>
    <nameField>
        <label>ObjectA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ObjectAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjectB__c/ObjectB__c.object-meta.xml
<CustomObject>
    <label>ObjectB</label>
    <nameField>
        <label>ObjectB Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ObjectBs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjectB__c/fields/ObjectA__c.field-meta.xml
<CustomField>
    <fullName>ObjectA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ObjectA</label>
    <referenceTo>ObjectA__c</referenceTo>
    <relationshipLabel>ObjectBs</relationshipLabel>
    <relationshipName>ObjectBs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ObjectC__c/ObjectC__c.object-meta.xml
<CustomObject>
    <label>ObjectC</label>
    <nameField>
        <label>ObjectC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ObjectCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjectC__c/fields/ObjectB__c.field-meta.xml
<CustomField>
    <fullName>ObjectB__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ObjectB</label>
    <referenceTo>ObjectB__c</referenceTo>
    <relationshipLabel>ObjectCs</relationshipLabel>
    <relationshipName>ObjectCs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RecordsListController.cls
public with sharing class RecordsListController {

    //get list of objects_B related to objects_A
    @AuraEnabled(Cacheable=true)
    public static ObjectB__c[] getObjectsB(Id recordId) {
        return [SELECT Id, Name, Phone__c, Age__c FROM ObjectB__c where objectA__c = :recordId];
    }

    //get list of objects_C related to objects_A
    @AuraEnabled(Cacheable=true)
    public static ObjectC__c[] getObjectsC(Id recordId) {
        return [SELECT Id, Name, Phone__c, Age__c FROM ObjectC__c where ObjectB__r.objectA__c = :recordId ];
    }

}